### PR TITLE
GH-61 Support extracting host value from wrapped HttpRequest

### PR DESCRIPTION
**Pull request by lukasniemeier-zalando**
Fixes GH-61.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
I'd unwrap the request recursively until you don't find a wrapper anymore.
In case somebody wraps it multiple times.

On 22 Mar 2017 17:24, "lukasniemeier-zalando" <notifications@github.com>
wrote:

Fixes GH-61 <https://github.com/zalando-incubator/put-it-to-rest/issues/61>.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/zalando-incubator/put-it-to-rest/pull/62
Commit Summary

   - GH-61 Support extracting host value from wrapped HttpRequest

File Changes

   - *M* src/main/java/org/zalando/putittorest/zmon/
   ZmonRequestInterceptor.java
   <https://github.com/zalando-incubator/put-it-to-rest/pull/62/files#diff-0>
   (15)
   - *M* src/test/java/org/zalando/putittorest/zmon/
   ZmonRequestInterceptorTest.java
   <https://github.com/zalando-incubator/put-it-to-rest/pull/62/files#diff-1>
   (13)

Patch Links:

   - https://github.com/zalando-incubator/put-it-to-rest/pull/62.patch
   - https://github.com/zalando-incubator/put-it-to-rest/pull/62.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zalando-incubator/put-it-to-rest/pull/62>, or mute the
thread

**Comment by lukasniemeier-zalando** [comment]
@whiskeysierra kk, updated!

**Comment by whiskeysierra** [comment]
:+1:

**Comment by lukasniemeier-zalando** [comment]
Thank you! What do you think of a bug fix release?

**Comment by whiskeysierra** [comment]
Already on it.

**Comment by whiskeysierra** [comment]
0.11.2 should be in central soon(tm).

**Pull request merged**
