### PR TITLE
Deferred plugin resolution

### LINKED ISSUE #64: Defer PluginResolver
**As** the `RestClientPostProcessor`
**I want** to defer usage of the `PluginResolver`
**So that** I do not violate the container by causing premature bean instantiation.

Currently the `RestClientPostProcessor` [depends](https://github.com/zalando-incubator/put-it-to-rest/blob/master/src/main/java/org/zalando/putittorest/RestClientAutoConfiguration.java#L26) on the `PluginResolver`, which seems to cause premature [bean instantiation](https://github.com/zalando-incubator/put-it-to-rest/blob/master/src/main/java/org/zalando/putittorest/DefaultPluginResolver.java#L30). [Documentation](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/beans/factory/config/BeanFactoryPostProcessor.html) states that a `BeanFactoryPostProcessor` should not do that.

I guess one of the effects of this is shown in the following log-line on startup:

```
Bean 'myBean' of type [class MyType] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

Can we defer resolving of the plugins?

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #64

- [x] Make exception and hystrix plugins really optional

### CODE REVIEW

**Comment by lukasniemeier-zalando** [comment]
The Coverage strikes back!

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by whiskeysierra** [comment]
@lukasniemeier-zalando Can you review the last commit?

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Pull request merged**
